---
title: "DNML1"
output: 
  flexdashboard::flex_dashboard:
    runtime: shiny
    vertical_layout: scroll
    orientation: columns
    theme:
      bg: "#ffffff"
      fg: "#180E3F"
      primary: "#9FA8DA"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
---

```{r setup, include=FALSE}
library(flexdashboard)
library(here)
library(caret)
library(readxl)
library(ggfortify)
library(GGally)
library(glmnet)
library(Hmisc)
library(plotly)
library(knitr)
library(shiny)
library(tidyverse)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

```{r include=FALSE}
db <- read_excel(here("data/dataform.xlsx"))
db <- na.omit(db)

db$ID <- as.factor(paste0(db$ID, ".", seq(1,length(db$ID)))) 
db$Group <- as.factor(db$Group) 



db <- db %>%
  select(-c("MitoCount", "TotArea", "Bcount", "TotPerim", "TotBLength", "Bjunct", "BEndP"))

long_db <- db %>%
  pivot_longer(cols = -c(ID, Group), names_to = "Predictor", values_to = "Value")

```

First Look {.tabset}
===========================================================

 sidebar {.sidebar}
------------------------------------------------------------

```{r}

selectInput("geomtype", "Select Plot Type", choices = c("Box plot", "Density plot"), selected = "Box plot")

```


Column
------------------------------------------------------------

### Distribution of each predictor

```{r}



renderPlotly({
  plt_type <- reactive(as.character(input$geomtype))
  
  p <- reactive({
    if (plt_type() == "Box plot") {
      long_db %>%
        ggplot(aes(x = Group, y = Value, fill = Group)) +
        geom_boxplot() +
        facet_wrap(~ Predictor, scales = "free") +
        scale_fill_manual(values = c("#a39b9b", "#67c7c5", "#f2de79")) +
        theme_classic() +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), legend.position = "none")
    } else {
      long_db %>%
        ggplot(aes(x = Value, fill = Group)) +
        geom_density(alpha = 0.6) +
        facet_wrap(~ Predictor, scales = "free") +
        scale_fill_manual(values = c("#a39b9b", "#67c7c5", "#f2de79")) +
        theme_classic() 
    }
  })
  
  ggplotly(p())
})

```

Variables are intercorrelated {.tabset}
=====================================================================

sidebar {.sidebar}
------------------------------------------------------------

```{r}

selectInput("corrplot", "Select Plot Type", choices = c("Correlation Matrix", "Hierarchical clustering"), selected = "Correlation Matrix")

```

Column {data-width="650"}
------------------------------------------------------------

```{r}
var_cor <- db %>%
  select(-c(ID, Group)) %>%
  ggcorr(label = TRUE, low = "#5499C7", high = "#BE0461", size =3) 


vclus <- varclus(as.matrix(db[-c(1,2)]))


groups <- cutree(vclus$hclust, 3)

red_vars <- redun(as.matrix(db[-c(1,2)]))

db_res <- db %>%
  select(c("ID", "Group", red_vars$In))

```


```{r}
## Rendering plots based on selected input
uiOutput("corr_plot")

output$corr_plot <- renderUI({
  if (input$corrplot == "Correlation Matrix") {
    plotlyOutput("plotly_corrplot")
  } else {
    plotOutput("ggplot_corrplot")
  }
})

output$plotly_corrplot <- renderPlotly({
  ggplotly(var_cor)
})

output$ggplot_corrplot <- renderPlot({
  plot(vclus)
})

```


```{r include=FALSE}
set.seed(2024)

db_ml <- db_res 


trnIndex <- createDataPartition(db_ml$Group, p = 0.7, list = FALSE)

trn <- db_ml[trnIndex,]
tst <- db_ml[-trnIndex,]

trn[-c(1,2)] <- scale(log2(trn[-c(1,2)]))
tst[-c(1,2)] <- scale(log2(tst[-c(1,2)]))

```


```{r include = FALSE}
set.seed(2024)

train_control <- trainControl(method="repeatedcv", number=10, repeats=3)

train_model <- function(dat, method, search_grid=NULL) {
  set.seed(2024)
  
  mdl <- train(Group ~ .,
               data = dat[-1], 
               method = method,
               tuneGrid = search_grid,
               trControl = train_control,
               trace = FALSE)
  
  return(mdl)
}

make_bound_plot <- function(mod, dat, pcx = 1, pcy = 2, alg) {
  set.seed(2024)  # Ensure reproducibility in PCA transformation

  preproc <- preProcess(dat[-c(1,2)], method = c("pca"))
  pca_transformed <- predict(preproc, dat[-c(1,2)])
  pca_transformed <- data.frame(pca_transformed, Reference = dat$Group, ID = dat$ID)

  colnames(pca_transformed)[pcx] <- "X"
  colnames(pca_transformed)[pcy] <- "Y"

  # Create a grid of points in the PCA-transformed space
  x_min <- min(pca_transformed$X) - 1
  x_max <- max(pca_transformed$X) + 1
  y_min <- min(pca_transformed$Y) - 1
  y_max <- max(pca_transformed$Y) + 1

  # Generate grid points
  grid <- expand.grid(X = seq(x_min, x_max, length.out = 100),
                      Y = seq(y_min, y_max, length.out = 100))

  # Combine the grid with zeros for other components
  grid_full <- data.frame(matrix(0, nrow = nrow(grid), ncol = ncol(pca_transformed)-2))
  colnames(grid_full) <- colnames(pca_transformed)[-c(ncol(pca_transformed)-1, ncol(pca_transformed))]
  grid_full[, c(pcx, pcy)] <- grid

  # Inverse transform the grid to the original feature space
  inverse_pca <- function(pca_model, pca_data) {
    center <- pca_model$mean
    scale <- pca_model$std
    rotation <- pca_model$rotation

    # Calculate the original data matrix
    original_matrix <- as.matrix(pca_data) %*% t(rotation)

    # Re-scale and re-center
    original_matrix <- sweep(original_matrix, 2, scale, `*`)
    original_matrix <- sweep(original_matrix, 2, center, `+`)

    return(as.data.frame(original_matrix))
  }

  # Perform inverse PCA transformation on the grid
  grid_original <- inverse_pca(preproc, grid_full)
  colnames(grid_original) <- colnames(dat[-c(1,2)])

  # Predict on the original feature space
  grid_original$Prediction <- predict(mod, grid_original, type = "raw")
  grid$Prediction <- grid_original$Prediction
  labels_df <- data.frame(ID = dat$ID, Reference = dat$Group)


  # Plot the decision boundary
  p = ggplot() +
    geom_tile(data = grid, aes(x = X, y = Y, fill = Prediction), alpha = 0.3) +
    geom_point(data = pca_transformed, aes(x = X, y = Y, color = Reference,  ID = ID), size = 2) +
    labs(title = paste(alg, "Decision Boundary with PCA"),
         x = paste("Principal Component", pcx),
         y = paste("Principal Component", pcy)) +
    theme_minimal() +
    scale_color_manual(labels = c("Control", "DNML1", "OTHERMIT"), values = c("#a39b9b",  "#67c7c5", "#f2de79")) +
    scale_fill_manual(labels = c("Control", "DNML1", "OTHERMIT"), values = c("#a39b9b",  "#67c7c5", "#f2de79")) +
    theme(legend.position = "none")
  
    ggplotly(p, tooltip = c("color", "ID", "fill"))
    
  
}

```


Neural Network Multinomial Regression {.tabset}
=======================================================================

```{r}
set.seed(2024)

search_grid <- expand.grid(
  decay = seq(0, 0.2, by = 0.01)
)

multi_model <- train_model(trn, "multinom", search_grid)

pred_multi_model <- data.frame(Prediction = predict(multi_model, newx = as.matrix(trn[-c(1,2)]), type="raw"))

trn_class_res <- data.frame(ID = trn$ID, Prediction = pred_multi_model, Reference = trn$Group)

cfm <- confusionMatrix(predict(multi_model), trn$Group, positive = "DNML1")

```



Sidebar {.sidebar}
------------------------------------------------------------

```{r}

selectInput("xpc_1", "Select principal component for x-axis:", choices = c(1, 2, 3), selected = 1)
selectInput("ypc_1", "Select principal component for y-axis:", choices = c(1, 2, 3), selected = 2)

```


Column {data-width="650"}
------------------------------------------------------------

### Decision Boundary 

```{r}

uiOutput("plot_1")

output$plot_1 <- renderUI({
  plotlyOutput("plotly_plot_1")
})

output$plotly_plot_1 <- renderPlotly({
  make_bound_plot(multi_model, trn, as.integer(input$xpc_1), as.integer(input$ypc_1), "Neural Network")
})


```


### Accuracy

```{r}
knitr::kable(cfm$table)

```


### Variable Importance

```{r}
knitr::kable(varImp(multi_model)[1])
```


Random Forest {.tabset}
====================================================================

```{r}
set.seed(2024)

search_grid <- expand.grid(
  mtry = seq(1, 4, by = 1)
)

rf_model <- train_model(trn, "rf", search_grid)

cfm_2 <- confusionMatrix(predict(rf_model), trn$Group, positive = "DNML1")


```

Sidebar {.sidebar}
------------------------------------------------------------

```{r}
selectInput("xpc_2", "Select principal component for x-axis:", choices = c(1, 2, 3), selected = 1)
selectInput("ypc_2", "Select principal component for y-axis:", choices = c(1, 2, 3), selected = 2)
```


Column {data-width="650"}
------------------------------------------------------------
 
### Decision Boundary 
 
```{r}
uiOutput("plot_2")

output$plot_2 <- renderUI({
  plotlyOutput("plotly_plot_2")
})

output$plotly_plot_2 <- renderPlotly({
  make_bound_plot(rf_model, trn, as.integer(input$xpc_2), as.integer(input$ypc_2), "Random Forest")
})
```
 
### Accuracy
 
```{r}

knitr::kable(cfm_2$table)

```

### Variable Importance

```{r}
knitr::kable(varImp(rf_model)[1])
```


# SVM

```{r}
set.seed(2024)



# Preprocess with PCA and train SVM model
svm_model <- train_model(trn, "svmLinear")



pred_svm <- predict(svm_model, as.matrix(trn[-c(1,2)]), type = "raw")

# confusionMatrix(pred_svm, trn$Group, positive = "DNM1L")


```
